---
title: "SK Dem Data"
output: pdf_document
date: "2025-10-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(tidyverse)
library(lubridate)
library(fixest)
library(broom)
library(splines)
library(ggplot2)
library(patchwork)
library(modelsummary)
library(dplyr)
library(lfe)
library(ggrepel)
library(vistime)
library(vdemdata)
library(haven)
library(accessibility)
```

```{r}
# manual placeholder table, insert different one later

#add quantity variable so can use for repeats in same month of same event type
nk_events <- tibble::tribble(
  ~event_date, ~event_name, ~event_type,
  as.Date("1956-01-01"), "Soviet nuclear training begins", "nuclear_activity",
  as.Date("1959-01-01"), "USSR–DPRK nuclear cooperation agreement", "nuclear_activity",
  as.Date("1984-04-09"), "Hwasong-5 missile test", "weapons_test",
  as.Date("1984-08-01"), "Hwasong-5 missle launch", "weapons_test",
  as.Date("1993-05-29"), "Hwasong-6 and Hwasong-7 test-fires", "weapons_test",
  as.Date("1998-08-31"), "Unha-1 rocket ballistic missile launch", "weapons_test",
  as.Date("1990-12-01"), "High-explosives tests at Yongbyon", "weapons_test",
  as.Date("2005-05-01"), "Missile fired into Sea of Japan", "military_attack",
  as.Date("2006-03-08"), "Short-range missile tests into Sea of Japan", "weapons_test",
  as.Date("2006-07-05"), "Taepodong-2 test-fire", "weapons_test",
  as.Date("2007-05-25"), "Short-range missiles fired", "weapons_test",
  as.Date("2006-10-09"), "First Nuclear Test", "nuclear_test",
  as.Date("2009-05-25"), "Second Nuclear Test", "nuclear_test",
  as.Date("2010-11-23"), "Yeonpyeong Shelling", "military_attack",
  as.Date("2013-02-12"), "Third Nuclear Test", "nuclear_test",
  as.Date("2016-01-06"), "Fourth Nuclear Test", "nuclear_test",
  as.Date("2016-09-09"), "Fifth Nuclear Test", "nuclear_test",
  as.Date("2017-09-03"), "Sixth Nuclear Test", "nuclear_test",
  as.Date("2020-10-10"), "ICBM Unveiled", "nuclear_activity",
  as.Date("2022-01-05"), "Hypersonic missile test", "weapons_test",
  as.Date("2023-03-27"), "Hwasan-31 Announcement", "nuclear_activity",
)

```

```{r}
timeline_data <- nk_events %>%
  mutate(
    start = event_date,
    end = event_date,   
    label = event_name,
    group = event_type
  ) %>%
  select(label, start, end, group)


vistime(timeline_data,
        col.group = "group",
        col.label = "black",
        show_labels = FALSE,
        rotate_labels = FALSE,
        col.legend = "group",
        title = "Timeline of North Korean Nuclear Program")

```

```{r}
survey_dates <- survey %>%
  distinct(year) %>%
  mutate(survey_date = as.Date(paste0(year, "-06-15")))

```

```{r}
survey_event <- expand.grid(year = unique(survey_dates$year),
                            event_date = nk_events$event_date) %>%
  left_join(survey_dates, by = "year") %>%
  left_join(nk_events, by = "event_date") %>%
  mutate(days_since_event = as.numeric(survey_date - event_date)) %>%
  filter(days_since_event >= 0)
```

```{r}

lambda <- log(2) / 180

survey_event <- survey_event %>%
  mutate(decay_weight = exp(-lambda * days_since_event))

linear <- decay_linear(cutoff = 50)
#cutoff is a placeholder

#make decay_weight be 0 after a set time

#add d_weight_check to print out a table of values after decay weight is applied to see if it's printing out right
```

```{r}

year_event_impact <- survey_event %>%
  group_by(year) %>%
  summarise(
    total_events = n(),
    weighted_event_intensity = sum(decay_weight, na.rm = TRUE),
    recent_event = min(days_since_event, na.rm = TRUE)
  )
survey_model <- survey %>%
  left_join(year_event_impact, by = "year")

survey_model_clean <- survey_model %>%
  filter(year %in% c(2003, 2004, 2005, 2010))

```

```{r}

model <- felm(
  north_policy_eval ~ weighted_event_intensity | year,
  data = survey_model_clean
)
summary(model)

year_summary <- survey_model_clean %>%
  group_by(year) %>%
  summarize(
    mean_eval = mean(north_policy_eval, na.rm = TRUE),
    event_intensity = mean(weighted_event_intensity, na.rm = TRUE)
  )

lm(mean_eval ~ event_intensity, data = year_summary)

```

```{r}

vdem_kor <- vdem %>%
  filter(country_id == 42)

vdem_rok <- vdem_kor %>%
  filter(histname == "Republic of Korea")

vdem_rok_dem <- vdem_rok %>%
  select(
    year,
    v2x_polyarchy,
    v2x_libdem,
    v2x_partipdem, 
    v2x_delibdem,  
    v2x_rule,   
    v2x_jucon,      
    v2xlg_legcon,        
    v2x_civlib, 
    v2x_clphy,
    v2x_freexp_altinf 
  )

vdem_rok_dem
```


```{r}

vdem_long <- vdem_rok_dem %>%
  pivot_longer(
    cols = c(
      v2x_polyarchy,
      v2x_libdem,
      v2x_partipdem,
      v2x_delibdem
    ),
    names_to = "index",
    values_to = "value"
  )

```

```{r}
ggplot(vdem_long, aes(x = year, y = value, color = index)) +
  geom_line(linewidth = 1.1) +
  theme_minimal() +
  labs(
    title = "Democracy Indices in South Korea",
    x = "Year",
    y = "Index Value (0–1)",
    color = "Index"
  )

```

```{r}
vdem_rights <- vdem_rok_dem %>%
  select(
    year,
    v2x_rule,
    v2x_civlib,
    v2x_freexp_altinf
  ) %>%
  pivot_longer(-year, names_to = "index", values_to = "value")

ggplot(vdem_rights, aes(year, value, color = index)) +
  geom_line(linewidth = 1.2) +
  theme_minimal() +
  labs(
    title = "Rule of Law and Civil Liberties in South Korea",
    x = "Year",
    y = "Index Value (0–1)",
    color = ""
  )

```

```{r}
nk_years <- nk_events %>%
  mutate(year = lubridate::year(event_date)) %>%
  filter(year %in% vdem_rok_dem$year)

ggplot(vdem_rok_dem, aes(x = year, y = v2x_libdem)) +
  geom_line(linewidth = 1.2, color = "steelblue") +
  geom_vline(
    data = nk_years,
    aes(xintercept = year),
    linetype = "dashed",
    alpha = 0.5
  ) +
  theme_minimal() +
  labs(
    title = "Liberal Democracy in South Korea and North Korean Events",
    x = "Year",
    y = "Liberal Democracy Index (0–1)"
  )

```
```{r}
nk_events_year <- nk_events %>%
  filter(!is.na(event_date)) %>%
  mutate(year = year(event_date))

nk_yearly <- nk_events_year %>%
  group_by(year) %>%
  summarise(
    n_events = n(),
    n_nuclear = sum(event_type == "nuclear_test"),
    n_weapons = sum(event_type == "weapons_test"),
    n_attacks = sum(event_type == "military_attack")
  )

vdem_macro <- vdem_rok_dem %>%
  left_join(nk_yearly, by = "year")

vdem_macro <- vdem_macro %>%
  mutate(
    n_events = replace_na(n_events, 0)
  )

```

```{r}

# NO SCALED EVENTS 

ggplot(vdem_macro, aes(x = n_events, y = v2x_libdem)) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  labs(
    title = "North Korean Security Events and Liberal Democracy",
    x = "Number of NK Events (Year)",
    y = "Liberal Democracy Index"
  )

```
Without taking intensity into consideration, liberal democracy tends to increase. Possibly has some relation with South Korea's rapid industrialization and democratization periods? Think about cutting off pre-2000s data.

```{r}
vdem_compare <- vdem_rok_dem %>%
  select(
    year,
    v2x_polyarchy,
    v2x_libdem,
    v2x_rule
  ) %>%
  pivot_longer(-year, names_to = "index", values_to = "value")

ggplot(vdem_compare, aes(year, value, color = index)) +
  geom_line(linewidth = 1.2) +
  theme_minimal() +
  labs(
    title = "Electoral Democracy vs Liberal Constraints in South Korea",
    x = "Year",
    y = "Index (0–1)"
  )

```


